# Generated by Django 2.1.5 on 2020-12-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_no', models.IntegerField(default=1007, primary_key=True, serialize=False)),
                ('flight_id', models.CharField(max_length=50)),
                ('airline_name', models.CharField(max_length=50)),
                ('no_of_seats', models.IntegerField(default=0)),
                ('source', models.CharField(max_length=50)),
                ('source_code', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=50)),
                ('destination_code', models.CharField(max_length=3)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(default=0.0005025125628140704)),
                ('nationality', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('checked_in_status', models.BooleanField(default=0)),
                ('cleared_security_status', models.IntegerField(default=0)),
                ('flight_no', models.ForeignKey(default=1007, on_delete=django.db.models.deletion.CASCADE, to='user.Flight')),
            ],
        ),
    ]
