# Generated by Django 2.1.5 on 2021-01-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_flight_flight_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_id',
            field=models.TextField(null=True),
        ),
    ]
