# Generated by Django 2.1.5 on 2021-01-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_flight_flight_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='checked_in_status',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='cleared_security_status',
        ),
    ]
