# Generated by Django 2.1.5 on 2021-01-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210106_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_no',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='ticket_class',
            field=models.TextField(null=True),
        ),
    ]
