# Generated by Django 2.1.5 on 2021-01-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210106_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
