# Generated by Django 2.1.5 on 2021-01-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210106_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='seats',
            field=models.IntegerField(default=1),
        ),
    ]
