# Generated by Django 2.1.5 on 2021-01-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_passenger_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='pay_option',
            field=models.TextField(null=True),
        ),
    ]
