# Generated by Django 2.1.5 on 2021-01-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_passenger_card_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='expiration',
            field=models.DateField(null=True),
        ),
    ]
