# Generated by Django 2.1.5 on 2021-01-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_passenger_cvv'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
